# Generated by Django 4.2.7 on 2025-04-30 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('code_js', models.TextField(blank=True, help_text='JavaScript code for the simulation')),
                ('code_python', models.TextField(blank=True, help_text='Python code for the simulation')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration parameters for the simulation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='core.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='code', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('texture', 'Texture'), ('model', '3D Model'), ('sound', 'Sound'), ('data', 'Data File')], max_length=20)),
                ('file', models.FileField(upload_to='simulation_assets/')),
                ('description', models.TextField(blank=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='simlab.simulation')),
            ],
        ),
        migrations.AddField(
            model_name='simulation',
            name='simulation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='simlab.simulationtype'),
        ),
        migrations.CreateModel(
            name='UserSimulationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text="User's saved simulation data")),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='simlab.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'simulation')},
            },
        ),
    ]
